/* tslint:disable */
/* eslint-disable */
// @ts-nocheck
/**
 * Ampli - A strong typed wrapper for your Analytics
 *
 * This file is generated by Amplitude.
 * To update run 'ampli pull web'
 *
 * Required dependencies: @amplitude/analytics-browser@^1.3.0
 * Tracking Plan Version: 1
 * Build: 1.0.0
 * Runtime: browser:typescript-ampli-v2
 *
 * [View Tracking Plan](https://data.amplitude.com/igor-goncalves/Amplitude%20Test/events/first-branch-test/latest)
 *
 * [Full Setup Instructions](https://data.amplitude.com/igor-goncalves/Amplitude%20Test/implementation/web)
 */

import * as amplitude from '@amplitude/analytics-browser';

export type Environment = 'amplitudetest';

export const ApiKey: Record<Environment, string> = {
  amplitudetest: 'e56a40db8df5e06df7b09e1e4d6f461b'
};

/**
 * Default Amplitude configuration options. Contains tracking plan information.
 */
export const DefaultConfiguration: BrowserOptions = {
  plan: {
    version: '1',
    branch: 'first-branch-test',
    source: 'web',
    versionId: '61677001-f0c3-439e-a75a-e10937634456'
  },
  ...{
    ingestionMetadata: {
      sourceName: 'browser-typescript-ampli',
      sourceVersion: '2.0.0'
    }
  }
};

export interface LoadOptionsBase { disabled?: boolean }

export type LoadOptionsWithEnvironment = LoadOptionsBase & { environment: Environment; client?: { configuration?: BrowserOptions; }; };
export type LoadOptionsWithApiKey = LoadOptionsBase & { client: { apiKey: string; configuration?: BrowserOptions; } };
export type LoadOptionsWithClientInstance = LoadOptionsBase & { client: { instance: BrowserClient; } };

export type LoadOptions = LoadOptionsWithEnvironment | LoadOptionsWithApiKey | LoadOptionsWithClientInstance;

export interface CitySelectedProperties {
  /**
   * City selected by user
   */
  city: string;
}

export interface LogMessageTriggeredProperties {
  /**
   * Any label used in buttons elements
   */
  label: string;
  /**
   * Message trigered when the event is triggered by user.
   */
  log_message: string;
}

export class CitySelected implements BaseEvent {
  event_type = 'City Selected';

  constructor(
    public event_properties: CitySelectedProperties,
  ) {
    this.event_properties = event_properties;
  }
}

export class LogMessageTriggered implements BaseEvent {
  event_type = 'Log Message Triggered';

  constructor(
    public event_properties: LogMessageTriggeredProperties,
  ) {
    this.event_properties = event_properties;
  }
}

export type PromiseResult<T> = { promise: Promise<T | void> };

const getVoidPromiseResult = () => ({ promise: Promise.resolve() });

// prettier-ignore
export class Ampli {
  private disabled: boolean = false;
  private amplitude?: BrowserClient;

  get client(): BrowserClient {
    this.isInitializedAndEnabled();
    return this.amplitude!;
  }

  get isLoaded(): boolean {
    return this.amplitude != null;
  }

  private isInitializedAndEnabled(): boolean {
    if (!this.amplitude) {
      console.error('ERROR: Ampli is not yet initialized. Have you called ampli.load() on app start?');
      return false;
    }
    return !this.disabled;
  }

  /**
   * Initialize the Ampli SDK. Call once when your application starts.
   *
   * @param options Configuration options to initialize the Ampli SDK with.
   */
  load(options: LoadOptions): PromiseResult<void> {
    this.disabled = options.disabled ?? false;

    if (this.amplitude) {
      console.warn('WARNING: Ampli is already intialized. Ampli.load() should be called once at application startup.');
      return getVoidPromiseResult();
    }

    let apiKey: string | null = null;
    if (options.client && 'apiKey' in options.client) {
      apiKey = options.client.apiKey;
    } else if ('environment' in options) {
      apiKey = ApiKey[options.environment];
    }

    if (options.client && 'instance' in options.client) {
      this.amplitude = options.client.instance;
    } else if (apiKey) {
      this.amplitude = amplitude.createInstance();
      const configuration = (options.client && 'configuration' in options.client) ? options.client.configuration : {};
      return this.amplitude.init(apiKey, undefined, { ...DefaultConfiguration, ...configuration });
    } else {
      console.error("ERROR: ampli.load() requires 'environment', 'client.apiKey', or 'client.instance'");
    }

    return getVoidPromiseResult();
  }

  /**
   * Identify a user and set user properties.
   *
   * @param userId The user's id.
   * @param options Optional event options.
   */
  identify(
    userId: string | undefined,
    options?: EventOptions,
  ): PromiseResult<Result> {
    if (!this.isInitializedAndEnabled()) {
      return getVoidPromiseResult();
    }

    if (userId) {
      options = {...options,  user_id: userId};
    }

    const amplitudeIdentify = new amplitude.Identify();
    return this.amplitude!.identify(
      amplitudeIdentify,
      options,
    );
  }

 /**
  * Flush the event.
  */
  flush() : PromiseResult<Result> {
    if (!this.isInitializedAndEnabled()) {
      return getVoidPromiseResult();
    }

    return this.amplitude!.flush();
  }

  /**
   * Track event
   *
   * @param event The event to track.
   * @param options Optional event options.
   */
  track(event: Event, options?: EventOptions): PromiseResult<Result> {
    if (!this.isInitializedAndEnabled()) {
      return getVoidPromiseResult();
    }

    return this.amplitude!.track(event, undefined, options);
  }

  /**
   * City Selected
   *
   * [View in Tracking Plan](https://data.amplitude.com/igor-goncalves/Amplitude%20Test/events/first-branch-test/latest/City%20Selected)
   *
   * This event is triggered when a user selects a city from a list or dropdown within the application. It captures the action of choosing a specific city to tailor content or settings accordingly.
   *
   * Owner: Igor dos Santos Gonçalves Silva
   *
   * @param properties The event's properties (e.g. city)
   * @param options Amplitude event options.
   */
  citySelected(
    properties: CitySelectedProperties,
    options?: EventOptions,
  ) {
    return this.track(new CitySelected(properties), options);
  }

  /**
   * Log Message Triggered
   *
   * [View in Tracking Plan](https://data.amplitude.com/igor-goncalves/Amplitude%20Test/events/first-branch-test/latest/Log%20Message%20Triggered)
   *
   * This event represents the system action of generating a log message. It is triggered whenever a log entry is created to record an application event, error, or status update.
   *
   * Owner: Igor Gonçalves
   *
   * @param properties The event's properties (e.g. label)
   * @param options Amplitude event options.
   */
  logMessageTriggered(
    properties: LogMessageTriggeredProperties,
    options?: EventOptions,
  ) {
    return this.track(new LogMessageTriggered(properties), options);
  }
}

export const ampli = new Ampli();

// BASE TYPES
type BrowserOptions = amplitude.Types.BrowserOptions;

export type BrowserClient = amplitude.Types.BrowserClient;
export type BaseEvent = amplitude.Types.BaseEvent;
export type IdentifyEvent = amplitude.Types.IdentifyEvent;
export type GroupEvent = amplitude.Types.GroupIdentifyEvent;
export type Event = amplitude.Types.Event;
export type EventOptions = amplitude.Types.EventOptions;
export type Result = amplitude.Types.Result;
